[package]
name = "rustache"
version = "0.1.0"
authors = ["Kile Deal <kile@kjdeal.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
